# Generated by Django 5.0.3 on 2024-04-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myMap', '0002_driver_remove_locations_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='car_make',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='driver',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='driver_images/'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_number',
            field=models.CharField(max_length=50),
        ),
    ]
