# Generated by Django 5.0.3 on 2024-04-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myMap', '0003_alter_driver_car_make_alter_driver_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='car_make',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_number',
            field=models.CharField(max_length=20),
        ),
    ]
