# Generated by Django 5.0.3 on 2024-04-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myMap', '0004_alter_driver_car_make_alter_driver_license_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='image',
        ),
        migrations.AddField(
            model_name='driver',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
