# Generated by Django 5.0.3 on 2024-04-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myMap', '0005_remove_driver_image_driver_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='image_url',
            new_name='image_url_1',
        ),
        migrations.AddField(
            model_name='driver',
            name='image_url_2',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='image_url_3',
            field=models.URLField(blank=True, null=True),
        ),
    ]
