# Generated by Django 5.0.3 on 2024-04-08 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myMap', '0006_rename_image_url_driver_image_url_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='image_url_1',
            new_name='image_url',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='image_url_2',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='image_url_3',
        ),
    ]
