# Generated by Django 5.0.3 on 2024-04-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myMap', '0007_rename_image_url_1_driver_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='image_url',
        ),
        migrations.AddField(
            model_name='driver',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='driver_images'),
        ),
    ]
